
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { prisma } from "@/lib/prisma";
import { unstable_noStore as noStore } from 'next/cache';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Force dynamic rendering to ensure theme updates are always fresh
export const dynamic = 'force-dynamic';

async function getActiveTheme() {
  noStore();
  try {
    const theme = await prisma.theme.findFirst({
      where: { isActive: true },
    });
    return theme;
  } catch (error) {
    console.error("Failed to fetch active theme:", error);
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  }>) {
  const activeTheme = await getActiveTheme();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider initialTheme={activeTheme as any}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
